Emily's people.html
HPQC-LABS/HPQC pull request #109
Opened 2023-07-20 11:28 UTC by EmilyyyLiang

First draft people.html is the latest one. I'll push a new commit after I have every photo. And please let me know if there are issues with the code that I haven't found so I can continue to change it. Also, I add Maheen's photo mistakenly, is it ok? If not I'll push a new commit.

2023-07-20 17:13 UTC, ndattani commented on people.html
> +                                <span>Undergraduate Researcher</span>
Why has Andreas changed from Masters to Undergrad?

2023-07-20 17:14 UTC, ndattani commented on people.html
> +                                <span>Undergraduate Researcher</span>
Is this accurate, according to the instructions?

2023-07-20 17:18 UTC, ndattani commented on people.html
> +                                <span>Undergraduate Researcher</span>
Sorry for writing "Undergraduate" in my instructions in the HPQC Discord server. We can stick with "Undergrad" which is what we had before. You can make that change, and then just commit that one change, and push it to the same fork of this repository, and the pull request should update automatically.

2023-08-02 15:17 UTC, sahanas02 approved these changes

2023-08-02 15:20 UTC, sahanas02 approved these changes

2023-08-02 15:26 UTC, sahanas02 approved these changes

2023-08-02 15:28 UTC, sahanas02 commented
.

2023-08-03 17:49 UTC, ndattani commented
We don't generally allow "Force pushing", like you did, and we have chosen the GitHub setting in the main fork, to not allow force pushing ***at all***. However, it seems that GitHub still allows force-pushing in your own fork of the repository, which is what you did. It's still not ideal to use force-pushing even if GitHub hasn't disabled you from being able to do it. In this case, by force-pushing we have lost the entire history in this pull reuqet, such as what the dates and times were when certain changes were ***first*** made. 

Anyway, another issue is that the diffs in your commit make it appear that every single line of people.html was removed and replaced with something new, when in fact this was not really the case. It's therefore hard to see what the real diffs are:

![image](https://github.com/HPQC-LABS/HPQC/assets/1163013/573bfc0e-e1aa-4e98-8d77-a739e4ef216e)

2023-08-04 17:24 UTC, ndattani commented on people.html
> +>>>>>>> 9e030c5aadce3fe4f82d40f925a3a22219bddc11
This is not right.

2023-08-04 18:46 UTC, ndattani requested changes

2023-08-04 18:46 UTC, ndattani commented on people.html
> +<<<<<<< HEAD
This is also wrong:
> `<<<<<< HEAD`

2023-08-08 07:05 UTC, ndattani commented
I see that @maheenandcode replaced people.html with the version from the main branch, then added your desired new people.html back, so that I can now see the diffs between the original people.html and your proposed new one. 

However, when I clicked on the "Files changed" tab (https://github.com/HPQC-LABS/HPQC/pull/109/files), it says that you're removing 1212 lines and adding 1346 lines, which among other things, would give inaccurate statistics here: https://github.com/HPQC-LABS/HPQC/graphs/contributors

![image](https://github.com/HPQC-LABS/HPQC/assets/1163013/c5497e9f-7a86-4a17-aa5d-80f354452cdd)

Do you know why this is happening?
Usually only the *actual* diffs would appear in the "Files changed" tab.
The problem seems to be this specific commit: https://github.com/HPQC-LABS/HPQC/pull/109/commits/62e0a11f044226f878d4871d82aa0152b8b10d36

Perhaps you can remove that specific commit?

2023-08-08 12:51 UTC, maheenandcode commented
Will do that!

2023-08-10 21:04 UTC, ndattani commented
The image of Karrar is now approved. We are just waiting for the fixed/cropped image of Mia.

2023-08-11 17:42 UTC, merged