Updates to error checking and fonts
HPQC-LABS/HPQC pull request #118
Opened 2023-08-15 19:46 UTC by sichaox

Added comments for readability.

2023-08-16 02:49 UTC, ndattani commented on tetrahedron.js
This title of this comit is "Did the upload properly" which would suggest that you're uploading the same file but in a different way, however the file has indeed changed, so this commit description isn't completely accurate.

2023-08-16 02:53 UTC, ndattani requested changes
😢 It looks like we're on the road to having this problem: https://github.com/HPQC-LABS/HPQC/pull/81#issuecomment-1512866564 again.

2023-08-16 02:56 UTC, ndattani commented
I'm not sure why this comment: https://github.com/HPQC-LABS/HPQC/pull/118/commits/f589ec434e0ae8d4728b2d2f44057b4d6a248ac0#r1295326140 is not appearing here.

2023-08-23 00:15 UTC, sichaox commented
> 😢 It looks like we're on the road to having this problem: [#81 (comment)](https://github.com/HPQC-LABS/HPQC/pull/81#issuecomment-1512866564) again.
I have removed .DS_Store file in the latest commit.

2023-08-23 00:15 UTC, sichaox commented on tetrahedron.js
I have used git ammend to rename the commit.

2023-09-28 14:02 UTC, merged